# Generated by Django 4.0.5 on 2022-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('image', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
    ]
