# Generated by Django 4.0.5 on 2022-06-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.CharField(choices=[('A', 'One Week'), ('B', 'One Month'), ('C', 'Three Months')], default='A', max_length=1)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bag')),
            ],
        ),
    ]
