# Generated by Django 4.0.5 on 2022-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rentals',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='rentals',
            name='date',
            field=models.DateField(verbose_name='Rental Start Date'),
        ),
        migrations.AddField(
            model_name='bag',
            name='renters',
            field=models.ManyToManyField(to='main_app.renter'),
        ),
    ]
